### ISSUE TITLE
Is this active?

### ISSUE THREAD

**Issue by JasonCrowe** [sguermond/amazon-advertising-api-python#2]
Hi Sarah, 
I got here through the original project. It looks like it hasn't been updated in 4 years. Your project hasn't seen any updates in a while, but I don't know if it's been abandoned or it's just working fine.

**Comment by danetrata-bvsecurity** [comment]
I'm using the library right now, and it seems to be working fine. I'm forking now to add in some v2 and v3 calls that are missing.

**Comment by sguermond** [comment]
Fell off the GitHub train while ramping up on a new job, sorry for the extremely delayed response. 
I can confirm that [hartjet/amazon-advertising-api-python](https://github.com/hartjet/amazon-advertising-api-python) is still active, it’s being maintained by a former coworker so it’s most likely to be similar to this version.
